### ISSUE TITLE
wont start on windows 2012

### ISSUE THREAD

**Issue by xfiodembo** [wildfly/wildfly-core#2063]
The Wildfly service terminated with the following service-specific error: 
The extended attributes are inconsistent.,
actually i tried to start via CLI, turns out JAVA_HOME was not properly set... the service start command should (if possible) write this instead of 'the extended properties are inconsistent'. took me a few days to realize i am pointing to a jdk instead of a JRE

**Comment by jamezp** [comment]
If this is an issue please file an issue at http://issues.jboss.org/browse/WFCORE. For questions please post to the forums https://developer.jboss.org/en/wildfly.

**Comment by pdb3s** [comment]
Thank you for posting this. You saved me a lot of time because I was setting this up on a new box that didn't have Java installed on it yet.
