### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by puntogil** [wildfly/wildfly-core#962]
hi
any ideas?

[DEBUG]   aesh (0.33.16): 0.33.15
[DEBUG]   aether-util (1.0.2): 1.0.0.v20140518
[DEBUG]   google-guice (3.2.5): 3.2.3
[DEBUG]   guava (18.0): 
[DEBUG]   jandex (1.2.2): 1.2.2.Final
[DEBUG]   jansi (1.11): 1.9
[DEBUG]   java-1.8.0-openjdk-devel (1.8.0.51)
[DEBUG]   jboss-common-core (2.2.22): 2.5.0.Final
[DEBUG]   jboss-dmr (1.3.0): 1.3.0.Final
[DEBUG]   jboss-invocation (1.2.1): 1.4.1.Final
[DEBUG]   jboss-logging (3.3.0): 3.2.1.Final
[DEBUG]   jboss-logging-tools (1.2.0): 2.0.0.Final
[DEBUG]   jboss-logmanager (2.0.0): 2.0.0.Final
[DEBUG]   jboss-marshalling (1.4.6): 1.4.10.Final
[DEBUG]   jboss-modules (1.3.3): 1.4.3.Final
[DEBUG]   jboss-msc (1.2.2): 1.2.6.Final
[DEBUG]   jboss-parent (11): 16
[DEBUG]   jboss-remoting (4.0.3): 4.0.9.Final
[DEBUG]   jboss-remoting-jmx (2.0.0): 2.0.1.Final
[DEBUG]   jboss-sasl (1.0.5): 1.0.5.Final
[DEBUG]   jboss-stdio (1.0.2): 1.0.2.GA
[DEBUG]   jboss-threads (2.1.0): 2.2.0.Final
[DEBUG]   jboss-vfs (3.2.5): 3.2.9.Final
[DEBUG]   log4j-jboss-logmanager (1.1.2): 1.1.2.Final
[DEBUG]   log4j (1.2.17): 1.2.16
[DEBUG]   picketbox (4.9.2): 4.9.2.Final
[DEBUG]   slf4j (1.7.10): 1.6.4
[DEBUG]   staxmapper (1.2.0): 1.2.0.Final
[DEBUG]   undertow (1.2.10): 1.2.9.Final
[DEBUG]   wildfly-security-manager (1.0.0): 1.1.2.Final
[DEBUG]   xnio (3.3.0): 3.3.1.Final

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project wildfly-logging: Compilation failure: Compilation failure:
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[143,36] no suitable constructor found for LoggingEvent(org.jboss.logmanager.ExtLogRecord,org.jboss.as.logging.logmanager.Log4jAppenderHandler.DummyCategory)
[ERROR] constructor org.apache.log4j.spi.LoggingEvent.LoggingEvent(java.lang.String,org.apache.log4j.Category,org.apache.log4j.Priority,java.lang.Object,java.lang.Throwable) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor org.apache.log4j.spi.LoggingEvent.LoggingEvent(java.lang.String,org.apache.log4j.Category,long,org.apache.log4j.Priority,java.lang.Object,java.lang.Throwable) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor org.apache.log4j.spi.LoggingEvent.LoggingEvent(java.lang.String,org.apache.log4j.Category,long,org.apache.log4j.Level,java.lang.Object,java.lang.String,org.apache.log4j.spi.ThrowableInformation,java.lang.String,org.apache.log4j.spi.LocationInfo,java.util.Map) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[195,42] cannot find symbol
[ERROR] symbol:   method getLogRecord()
[ERROR] location: variable event of type org.apache.log4j.spi.LoggingEvent
[ERROR] -> [Help 1]

thanks in advance

**Comment by puntogil** [comment]
aehm ...
forgot i added in the previous build log4j 1.2.17 in the pom file
without return this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project wildfly-logging: Compilation failure: Compilation failure:
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[165,26] cannot access org.apache.log4j.spi.AppenderAttachable
[ERROR] class file for org.apache.log4j.spi.AppenderAttachable not found
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/HandlerOperations.java:[50,24] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: package org.apache.log4j
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigDeploymentProcessor.java:[36,28] package org.apache.log4j.xml does not exist
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[28,24] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: package org.apache.log4j
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[30,24] cannot find symbol
[ERROR] symbol:   class Layout
[ERROR] location: package org.apache.log4j
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[32,28] cannot find symbol
[ERROR] symbol:   class OptionHandler
[ERROR] location: package org.apache.log4j.spi
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[45,22] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: class org.jboss.as.logging.logmanager.Log4jAppenderHandler
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[48,76] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: class org.jboss.as.logging.logmanager.Log4jAppenderHandler
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[59,39] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: class org.jboss.as.logging.logmanager.Log4jAppenderHandler
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[70,39] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: class org.jboss.as.logging.logmanager.Log4jAppenderHandler
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[83,12] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: class org.jboss.as.logging.logmanager.Log4jAppenderHandler
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[114,35] cannot find symbol
[ERROR] symbol:   class Appender
[ERROR] location: class org.jboss.as.logging.logmanager.Log4jAppenderHandler
[ERROR] wildfly-core-1.0.1.Final/logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java:[181,48] cannot find symbol
[ERROR] symbol:   class Layout
[ERROR] location: class org.jboss.as.logging.logmanager.Log4jAppenderHandler
[ERROR] -> [Help 1]

**Comment by ctomc** [comment]
We don't use github issues.
You should ether use mailing list, user forums or file jira report if you found bug.
see http://wildfly.org/gethelp/ for details where to get hold of team.

**Comment by jamezp** [comment]
This should be a forum question really, but you can't simply just replace log4j in this case.
